all: view
view:
	g++ -Werror -g -framework GLUT -framework OpenGL -framework Cocoa glut_viewer.cpp -o glut_viewer

test:
	g++ -Werror -g -framework GLUT -framework OpenGL -framework Cocoa main.cpp -o unittest
