all: view
view:
	g++ -Werror -O4 -framework GLUT -framework OpenGL -framework Cocoa glut_viewer.cpp -o glut_viewer

test:
	g++ -Werror -O4 -framework GLUT -framework OpenGL -framework Cocoa main.cpp -o unittest
